---
title: "POLI 110<br>Investigating Politics"
author: "Michael Weaver"
date: "January 5, 2019"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Course Introduction

## Today's Agenda

### 1. Personal Introduction

### 2. Course Learning Objectives

### 3. Course Expectations/Assignments

### 4. Course Policies

### 5. Registration/Questions

# Personal Introduction

## Who is this guy?

### Political Scientist (obviously)

### Research

- Political parties and ethnic/sectarian violence (India, Indonesia, Northern Ireland)
- Causes (and consequences) of changing public perception of lynching in the US
- War and changing racial boundaries in the US

### Approach

- History
- Rigorous statistical analysis
- "Big data"

# Course Learning Objectives

## Learning Objectives: Academic

- Understand what makes science distinct
- Identify questions answerable by science
- Master concepts surrounding problems and solutions to descriptive and causal inference
- Analyze and evaluate validity of descriptive and causal claims about politics

## Learning Objectives: Skills

- Memorize key concepts and tools used in political science
- Develop typologies to compare and contrast concepts/ideas

# Course Expectations

## Your grade

| Item             | Number | Fraction of Grade |
|------------------|--------|-------------------|
| Course Survey | 1 | 1% |
| Short Assignments | 4      | (4*10) 40%        |
| Midterm Exam     | 1      | 20%               |
| Final Exam | 1      | 30%               |
| Tutorial Participation | 1 | 9% |

## Key Dates




## Survey

### $\bullet$ Online invitation in Week 3

### $\bullet$ 1 point for *completion*

### $\bullet$ Use answers to illustrate key course concepts

## Short Assignments

### $\bullet$ Apply key concepts to your (constrained) choice of current events

### $\bullet$ Available on Canvas on Mondays at 9AM

### $\bullet$ Exactly 1 week to complete/upload to Canvas

### $\bullet$ Will be run through Turnitin

## Midterm Exam

### $\bullet$ **February 13** in class

### $\bullet$ Covers materials from weeks 2 to 5

### $\bullet$ Review session AND lists of key terms/questions 

## Final Exam

### $\bullet$ Date TBD

### $\bullet$ **Cumulative** over **entire course**, but **emphasizes** weeks 6 to 14.

### $\bullet$ Review session and key terms/questions

## Grading

### $\bullet$ **TAs**

### $\bullet$ **Rubrics**

### $\bullet$ **Validation**

### $\bullet$ **No "Curve"**

## What you need to do:

### $\bullet$ **Attend lecture:**

- slides not enough

### $\bullet$ **Attend Tutorial**

### $\bullet$ **Read**

### $\bullet$ **Canvas**

## What I will do:

### $\bullet$ **List of concepts**

### $\bullet$ **Slides**

### $\bullet$ **Speed**

### $\bullet$ **Discussion/Questions**

### $\bullet$ **Examples**


# Course Policies

## Missed Exam/ Late Assignments:

### $\bullet$ **Scheduling Conflict**

- Need to know ASAP to get a concession

### $\bullet$ **Arts Advising**

- Penalties unless given offical concession
- Ask Arts Advising first. Can be granted ex-post, but do it ASAP

### $\bullet$ **Lateness**

- non-catastrophic deduction (0.5 points out of 10 per 24 hours)

## Grade Appeals:

### $\bullet$ **To your TA**

### $\bullet$ **formal written letter** 

### $\bullet$ **48 hours waiting period**

### $\bullet$ **Grades can change $\Updownarrow$**

## Tutorial Attendance:

### $\bullet$ No participation without attendance

### $\bullet$ Make up absences/holidays by attending another Tutorial

- **notify both TAs**

### $\bullet$ Excused absences require official concession

- Each unexcused absence induces $(1/n * 100\%)$ deduction from total tutorial score
- $n$ is the number of **unexcused tutorial dates**

# Registration

## Where we stand:

As of this morning:

### 237/250; 13 reserved spots, 5 on waitlist

# Questions?


