---
title: "POLI 110<br>Investigating Politics"
author: "Michael Weaver"
date: "September 10, 2026"
output:
  ioslides_presentation:
    css: styles.css
    widescreen: true
    incremental: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Course Introduction

## Today's Agenda

1. Course Introduction
2. Course Expectations / Assignments
3. Course Policies
4. Questions

# Course Introduction

## Exercise

>- With your neighbors, discuss: what is the most important political problem facing the world today?
>- Discuss with your neighbors: how would you find out what is true about this issue? (be honest with yourself... how *would*, not how *should*)
>- Does this get at the actual "truth"? Why or why not?
>- What role should "truth" play in forming your opinion on this issue?

## Learning Objectives {.smaller}

- **Give reasons** for why truth is important in politics.
- **Identify** the types of claims made (implicitly or explicitly) in real-world political discourse.
- **Identify** which of these claims can be subject to scientific scrutiny.
- **Explain** what distinguishes scientific from unscientific forms of evidence.
- **Analyze** real-world descriptive and causal claims about politics, **identify** specific errors in the use of evidence, and **explain** *why* these errors occurred.
- **Analyze** real-world causal claims, **identify** the types of causal evidence provided, and **explain** the assumptions needed for this evidence to be valid.
- **Apply** these tools of analysis to **explain** how engaging critically with claims and evidence changes your opinion on the issue at hand.

## Thinking Practically

When you encounter media or a message, ask:

- Is this attempting to persuade me or change my behavior?
- What is this message attempting to get me to do or believe?
- How does it attempt to persuade or motivate me?
- Does the message employ claims and evidence?
- What could go wrong with this evidence?
- What would be **better** evidence?

## The Goal of This Course {.flexbox .vcenter}

<div class="big-question">
What is the ultimate goal of this course?
</div>

## A Note on Examples

**Examples used in class**

We will likely use many examples that come from the US and the Trump Administration:

- Why? *(two reasons)*
- No need for agreement

# Course Expectations

## Your Grade

| Item                    | Number | Points | Fraction of Grade |
|-------------------------|:------:|:------:|:------------------:|
| Short Assignments       |   3    |  2.5   |        7.5%          |
| Group Project           |   1    |   9    |         9%          |
| Course Survey           |   1    |   1    |         1%          |
| Midterm Study Guide        |   1   |  1   |        1%         |
| Final Study Guide    |   1    |  1.5    |        1.5%          |
| Midterm Exam            |   1    |  35    |        35%          |
| Final Exam              |   1    |  45    |        45%          |

## Reasoning

- Thanks, OpenAI, etc.
- Don't train LLMs to take your (future) job.
- LLMs are useful tools, but they won't cultivate critical thinking.
- AI tools (e.g. chatbots, Grammarly, etc.) are not permitted for any assignments, with one exception &mdash; welcome to use as a study aid.

## Key Dates

| Milestone       | Date              |
|-----------------|-------------------|
| Assignment 1    | September 28      |
| Assignment 2    | October 19        |
| Midterm Exam    | October 29        |
| Assignment 3    | November 23       |
| Assignment 4    | December 4       |
| Final Exam      | TBD               |

## Short Assignments

- Apply key concepts to your choice of current events
- Available on Canvas 1 week prior to due date @ 9 AM
- 1 week to complete and upload to Canvas

<div class="highlight">
Practice your understanding of course material, before exams.
</div>

## Group Project

- Ask and answer a question about a real problem facing students
- Develop, analyze, and interpret survey questions
- Work in 5&ndash;6 person groups
- Write a memo with incremental deadlines
- Overall grade weighted by personal contribution

<div class="highlight">
Work with others on your understanding of course material, before exams.
</div>

## Midterm Exam

- **October 29**, in class
- Covers material from weeks 1 to 7 (to October 20th)
- In-class / drop-in review session(s), plus a list of key terms and example questions

## Final Exam

- Date TBD
- **Cumulative** over the **entire course**, but **emphasizes** weeks 8 to 14
- Review session and key terms / example questions

## Exam Study

- Previous exams already available on Canvas
- Piazza to draft answers to these questions &mdash; collectively produce a study guide (points for completion)
- Piazza to ask any course-content related questions

## Grading

- **TAs** grade all assignments (except the group memo)
- **Rubrics** are used for consistency
- Grades undergo **validation**
- There is **no expected distribution**



## What You Need to Do {.smaller}

- **Attend Lecture (required)** 
    - Slides are not enough; reading is not enough &mdash; take thoughtful notes (not transcription)
    - Must attend 14 out of 21 lectures to take final; download iClicker.
- **Attend Drop-ins (recommended)**
    - Starts in **week 2**
    - Participate in group activity (survey writing)
- **Read** (helpful)
- Check **Canvas**
- Check **Piazza**

## No Tutorials: Optional Drop-ins

- Canvas survey: tell us your availability
- 6 time slots per week, no grade. (M-Th at 5 pm, starting next week)
- Sign-up to attend (b/c rules)
- Review material, ask questions.
- You may switch your tutorial time to new 5 pm drop-in to accommodate schedule

## What I Will Do

- Provide a **list of concepts** and review sessions
- Give you old exams; practice exam questions in lecture
- Post **slides** and deliver **lectures**
- Manage the **pace** of the lecture
- Encourage **discussion, questions, and examples**

# Course Policies

## Missed Exams / Late Assignments {.smaller}

- **Scheduling conflict**
    - Only applies to exams &mdash; notify me in advance
- **Unforeseen events**
    - Midterms/assignments in other courses are **not** "unforeseen"
    - Contact the professor &mdash; concessions can be prospective or retroactive
    - May direct you to Arts Advising for a concession
- **Lateness**
    - Non-catastrophic deduction: 5% **after** every 24 hours
    - Max penalty of 30% (after 1 week); **delayed grading**

## Late Policy: Reasons

1. Responsibility
2. Equity
3. Learning

## Grade Appeals

- Submit a **formal written letter**
- Direct it **to grading TA**
- **48-hour** waiting period required first
- Grades can change &uarr;&darr;

## Office Hours

Tuesdays, after lecture.

# Questions?
