---
title: "POLI 110"
author: "Michael Weaver"
date: "January 21, 2019"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# What can Science do?

## Plan for Today

### 1) Recap: Causal vs. Descriptive claims

### 2) Falsifiable/Unfalsifiable


# Recap

## Causal vs. Descriptive Claims

### Two varieties of empirical claims:

**descriptive claims:** claims about what exists (or has existed/will exist) in the world: 

**causal claims**: are claims about the how one phenomena ($X$) affects or causes another phenomena ($Y$). Causal claims state that $X$ **acts on** $Y$ in some way, not merely that they appear together in some pattern:


## Descriptive Claims

claims about what exists (or has existed/will exist) in the world: 

- what phenomena exist (what kinds of things exist?)
- what is the type of a specific phenomenon (what is this thing?)
- amount/frequency of phenomena (how much of something is there?)
- relative amount/frequency of phenomena across different places/times (how much of something is there here vs. there/now vs. then?)
- **what patterns are there in the shared appearance/non-appearance of different phenomena** (does this thing usually appear together with that other thing?) **do not conflate with causal claims**

## Causal Claims

- the **effect** that one thing or event has on another thing (effects of causes)
- the **cause** of some event or thing in the world (causes of effects)
- the *conditions* under which some thing or event *happens* (causes of effects)
- the *process* through which one thing affects another (causes of effects)

### Causal claims include some kind of  **causal verb (or phrase)**. E.g.:

### Causal claims always imply: *if* **we** could directly **manipulate** one thing $X$, then we would see $Y$ change

## Causal Claims

> "The chance of cancer **increases** with age"

Same as:

> "The chance of cancer **increases** <u>as</u> age **increases**"

### Is this a **causal** claim? Why/Why not?

## Practice



## Causal Claims and Prescriptive Claims

You and your friend win a sum of money in a lottery

You and your friend agree: 

**the most important ethical goal is minimizing human suffering.** (*value judgment*)

### You disagree on what to do:

(1) We should donate mosquito nets to stop malaria (**prescriptive claim**)

(2) We should give money directly to impoverished people (**prescriptive claim**)

## Causal Claims and Prescriptive Claims

- Assuming less malaria is good, resources are finite
- What if mosquite nets **don't** prevent malaria, or cause **more harm** (tangling deaths)?
- Showing "Malaria nets does not reduce malaria" is informative!

#### **Accepting a prescriptive claim requires both a *value judgment* and accepting a *causal claim***

bonus term: **instrumental rationality**


# Falsifiability

## Which claims can science evaluate? {.build}

### \#NotAllEmpiricalClaims open to science

### 

## Falsifiability

### an empirical claim is  **falsifiable**...

if that claim can be shown to be wrong by a specific empirical test. Even if we never **do** show the claim is wrong, it is **falsifiable** if, in principle it could be shown to be wrong. 

- e.g. The Earth orbits the Sun

### an empirical claim is **unfalsifiable**...

if there is no empirical test that can be done to show the claim is wrong


## Falsifiability

### Because science considers alternatives/is open to being wrong...

we can only scientifically evaluate claims that can, **in principle** be shown to be wrong.

The **best** claims/theories are those that stand up to many tests to show them wrong.

No claims/theories are "proven", they have "not yet been proven wrong"

- invitation to challenge

## Falsification

### Contrast with **verification**

If we had an empirical claim, $H_1$ ($H$ for hypothesis)

and, if $H_1$ were true or valid, then it implies we should make certain empirical observations $O_1$

Verification says that

1.  $H_1 \rightarrow O_1$

2. We see $O_1$

3. Therefore, $H_1$ is valid

## Falsification

Many people reject **verification** because many different, incompatible claims are might imply the same observed evidence

1. $(H_1, H_2, \ldots, H_k) \rightarrow O_1$

2. If we observe $O_1$

3. $H_1$ is not proven

## Falsification

If a claim $H_1$ is falsfiable, there must be observable implication $O_1$ that, if it were untrue, would invalidate $H_1$. So, the logic of **falsification** is: 

1. $H_1 \rightarrow  O_1$
2. $not\ O_1$
3. Therefore, $not\ H_1$

## Examples

$H_1:$ **"Immigrants are coming across the border to kill you"** ~ [Donald Trump](https://www.vox.com/2019/1/8/18174782/trump-speech-immigration-border)

<u>**Verification**</u>

1. $H_1 \rightarrow$ Murder committed by an "illegal immigrant"

2. There has been a murder by an "illegal immigrant" [see here](https://globalnews.ca/video/4401017/trump-slams-illegal-immigration-cites-mollie-tibbetts-murder)

3. Therefore, "Immigrants are coming across the border to kill you"

## Examples

$H_1:$ **"Immigrants are coming across the border to kill you"** ~ Donald Trump
$H_2:$ **"One immigrant committed murder"**
$H_3:$ **"Two immigrants committed murder"**
$H_4:$ **"Immigrants are less prone to murder than native born citizens"**

<u>**Verification?**</u>

1. $(H_1, H_2, H_3, H_4 \dots H_k) \rightarrow$ Murder committed by an "illegal immigrant"

2. There has been a murder by an "illegal immigrant" [see here](https://globalnews.ca/video/4401017/trump-slams-illegal-immigration-cites-mollie-tibbetts-murder)

3. Therefore, $H_1, H_2, H_3, or\ H_4$ could be valid

## Examples

> $H1:$ "An invisible and undetectable Flying Spaghetti Monster created the universe "after drinking heavily". According to these beliefs, the Monster's intoxication was the cause for a flawed Earth. Furthermore, according to Pastafarianism, all evidence for evolution was planted by the Flying Spaghetti Monster in an effort to test the faith of Pastafarians."

<u>**Falsification?**</u>

1. $H_1 \rightarrow ?$

2. $?$

3. $?$

What observable implication of this could be proven wrong?

## Examples

> $H_1:$ "According to Pastafarian beliefs, pirates are absolute divine beings and the original Pastafarians. Global warming, earthquakes, hurricanes, and other natural disasters are a direct effect of the shrinking numbers of pirates since the 1800s."

<u>**Falsification**</u>

1. $H_1 \rightarrow$ Increase in Pirates would decrease Global Warming

2. $not$ Increase in Pirates produce decrease in Global Warming

3. $not \ H_1$

In principle, this is could be **falsified**. (What kind of claims is $H_1$?)

## Examples

> $H_1:$ "Human beings are rational actors who maximize their utility."

1. $H_1 \rightarrow$ People make decisions that maximize their expected monetary earnings.

2. In games, people choose to take monetary losses to punish people who violate expected social norms ($not \ O_1$)

3. $not \ H_1$?

4. Frequently, scholars say: utility functions also place value on adherence to social norms (preferences over process, not outcome)

- Rational choice theories may not be falsifiable