---
title: "POLI 110"
author: "Michael Weaver"
date: "October 23, 2024"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
require(haven)
require(data.table)
require(ggplot2)
require(magrittr)
```


# Causal Claims

## Today

### **1. Introduction to Causality**

- **What is causality?**
- **Counterfactuals**
- **Potential Outcomes**

# Why Causality?

## Why causality?

Weber's insights:

### 1. **science is about prediction**

### 2. **science cannot tell us what to do**, but it can provide **clarity**

## Why causality?

If power is about giving us motivation **to do *something* **, then justifications include claims about the *consequences* of actions.

---

<iframe width="560" height="315" src="https://www.youtube.com/embed/N5jOBdge8yY?si=yJ-9wNqJBe2hhMMQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>


## Causal claims answer causal questions

<h3><ol>
<li> What are the **causes** of **effects**?
</ol></h3>

Want to explain something specific that has happened/we observe (**the effect**). Seek to **attribute** a cause for something we observe. 

- Why did Russia invade Ukraine?
- Why are housing prices  high in Vancouver?

## Causal claims answer causal questions

<h3><ol start=2>
<li> What are the **effects** of **causes**?
</ol></h3>

We want to know what happens if we do some action or some action (**the cause**) happens. This is about the **consequences** of some action.

- Has BC's housing speculation tax reduced housing prices? 
- What are the effects of restricting gun ownership on gun violence?

## Two ways of asking causal questions

### Looking at **effects of causes** versus **causes of effects**  leads to different approaches to scientific investigation

**causes of effects**
$$\textrm{?} \xrightarrow{} \textrm{effect}$$

**effects of causes**
$$\textrm{cause} \xrightarrow{} \textrm{?}$$


## Why Causality?

Not only is understanding causality important:

- scientific evidence for causal claims is difficult to obtain
- all the same problems as evidence for descriptive claims
- **and** new difficulties we must overcome

To understand the **problems** and **solutions** for providing evidence of causality, we need to know what it is.

# What is causality?

## What is causality?

### all **causal claims** are a combination of two specific descriptive claims

<br>

- sometimes these descriptive claims are made **explicit**, often they are **implied**.

## What is causality?

Why does the US have the highest rate of gun deaths among developed countries?

> **The US has the highest rate of gun deaths among developed countries because of its lax gun laws.**

- is this a question about "causes of effects" or "effects of causes"?
- What are the two descriptive claims in this causal claim?

## What is causality?

- Does building a wall to keep immigrants out reduce violent crime?

> **The border city of El Paso, Tex., used to have extremely high rates of violent crime — one of the highest in the entire country, and considered one of our nation’s most dangerous cities. Now, immediately upon its building, with a powerful barrier in place, El Paso is one of the safest cities in our country.** - Donald Trump

- is this a question about "causes of effects" or "effects of causes"?
- What are the two descriptive claims in this causal claim?

## What is causality?

The **descriptive claims** embedded in **causal claims** are of a specific type:

1. One is a claim about how the world *actually* is (**factual**)
2. One is a claim about how the world *would* be, if something were changed (**counterfactual**)

### **counterfactuals** are the key to causality

# Counterfactuals

## Causality is Counterfactual

### **What does that mean?**

## Counterfactuals and Causality:

**counterfactuals**: are the way world **would be** if events had transpired differently (other than what actually took place).

- imagine an "alternate universe" or "alternate timeline"

contrasts to what is **factual**: the way the world is, given the events that have taken place.

#

<iframe width="560" height="315" src="https://www.youtube.com/embed/Da-Mizk86AE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

# Spoiler Warning!

## Counterfactuals:

If Gwyneth Paltrow's character...

(a) **catches the train** then she catches her boyfriend cheating, and **dumps him**

(b) **does not catch the train** then she does not catch her boyfriend cheating, and **stays with him**

In reality, only **one** of these possibilities can happen. If (a) happens, it is **factual**, (b) is **counterfactual**

## An exercise {.build}

**Does knowing transgender people increase support for funding gender-affirming care?**

### Think and write...

In the 2023 AMS election, UBC students were asked vote on whether to increase student fees by \$8 to cover gender-affirming care.

Imagine: If you had a friend on campus who was trans/non-binary, would you have voted "yes" on this measure?

Imagine: If you did not have a friend on campus who was trans/non-binary, would you have voted "yes" on this measure?

Go to [menti.com](menti.com) and enter $6331 \ 4539$ (there are multiple questions, click through to answer all)

## An exercise

**Which of these is factual? Which is counterfactual**?

$1.$ If you had a friend on campus who was trans/non-binary, would you vote "yes" on this measure?

$2.$ If you did not have a friend on campus who was trans/non-binary, would you vote "yes" on this measure?

>- **It depends**: If you actually have a trans/non-binary friend, then $1$ is **factual** ($2$ is **counterfactual**); If you actually don't have a trans/non-binary friend, then $2$ is **factual** ($1$ is **counterfactual**)

## Potential Outcomes

Counterfactuals can be described with **potential outcomes**:

If $X$ is a **variable** for a suspected cause (having a trans friend) and $Y$ is a **variable** for what is possibly affected (voting for fee increase)... 

then **potential outcomes** are the values of $Y$ that a **specific case** would take for the different possible values of $X$ (factual and counterfactual):

- If **you** had a friend on campus who was trans/non-binary, would **you** vote "yes" on this measure?
-  If **you** did not have a friend on campus who was trans/non-binary, would **you** vote "yes" on this measure?

## Potential Outcomes

**potential outcomes notation:**

Where $i$ corresponds to a specific case (e.g., **you**, Gwyneth Paltrow)

$\text{Trans Friend}$ ($X$) is the causal variable (and can take different values, e.g. $yes, no$), then the potential outcomes of $\mathrm{\$8 \ fee \ vote}$ ($Y_i$) are:

$$\mathrm{AMS \ fee \ vote}_{i}(\text{Trans Friend} = yes),\\ \mathrm{AMS \ fee \ vote}_i(\text{Trans Friend} = no)$$

For person $i$, $\text{Trans  Friend}$ can only ever be $yes$ or $no$: one potential outcome is **factual** (it will happen), while the other will remain **counterfactual** (it won't happen)

$^*$ Note, I will use $\color{red}{red}$ to indicate counterfactual potential outcomes 

## Potential Outcomes

$\mathrm{Love \ Life _{Gwyneth} (Catches \ the \ train )}$
$= \mathrm{Dump \ cheating \ BF}$

$\mathrm{Love \ Life _{Gwyneth} (Doesn't \ catch \ the \ train )}$
$= \mathrm{Stay \ with \ cheating \ BF}$


We only will observe **one** of these two possibilities. But both could **potentially** have happened.


## Potential Outcomes

For any suspected cause $X$, and affected variable $Y$, and case $i$,  we denote potential outcomes as:

$$Y_i(X = ?)$$



---

<div style='position: relative; padding-bottom: 56.25%; padding-top: 35px; height: 0; overflow: hidden;'><iframe sandbox='allow-scripts allow-same-origin allow-presentation' allowfullscreen='true' allowtransparency='true' frameborder='0' height='315' src='https://www.mentimeter.com/app/presentation/e789a9ce6276b9aa8f508044b5f1bd11/embed' style='position: absolute; top: 0; left: 0; width: 100%; height: 100%;' width='420'></iframe></div>

---

**Draw potential outcomes on the board**

## Potential Outcomes: Caveat

In our example of having transgender friends and support for trans health care:

- We are only **imagining**, as if omniscient, what you would do in the alternate universe where you **do**(**do not**) have a trans friend
- Potential outcomes are what **you actually would do** in that alternate universe.

Even if we **don't know** how you would vote if you **did**(**did not**) have a trans friend, we can imagine that there is potential outcome of what you would do...

---

### **What do counterfactuals have to do with causality????**

## Causal Claims

Recall that causal claims are about how some shifting some factor **changes** something outcome...

## Counterfactuals and Causality:

**counterfactual causality**

We can say that $Y$ changes *because of* $X$ only if, for case $i$,  $Y_i(X = 1) \neq Y_i(X = 0)$:

- $X$ causes $Y$ if case $i$ would have behaved ($Y$) differently (than it did factually) in the (**counterfactual**) alternate universe where **everything was the same** except $X$ was changed.

REVISIT THE BOARD

# Example:

---

Counterfactuals Example

> **"The border city of El Paso, Tex., used to have extremely high rates of violent crime — one of the highest in the entire country, and considered one of our nation’s most dangerous cities. Now, immediately upon its building, with a powerful barrier in place, El Paso is one of the safest cities in our country."** - Donald Trump



- What is the "case"?
- What is the variable for the "cause"? What is the variable for the "effect"?


---

Counterfactuals Example

> **"The border city of El Paso, Tex., used to have extremely high rates of violent crime — one of the highest in the entire country, and considered one of our nation’s most dangerous cities. Now, immediately upon its building, with a powerful barrier in place, El Paso is one of the safest cities in our country."** - Donald Trump

Which of the potential outcomes are **factual**? **counterfactual**?

## Counterfactuals and Potential Outcomes

Trump's causal claim (implicitly): "The wall caused El Paso to have fewer murders".

Trump's counterfactual claim: "If there had been no wall, El Paso would have had more murders."

### Counterfactual claim implies two **potential outcomes**:

1. Number of murders in El Paso last year in the **presence** of the wall: $\textrm{Murders}_{\textrm{El Paso}}(\textrm{Wall})$
2. Number of murders in El Paso last year in the **absence** of the wall $\color{red}{\textrm{Murders}_{\textrm{El Paso}}(\textrm{No Wall})}$

If the claim is true... what are the (relative) **values** these potential outcomes should take?

## Counterfactuals and Potential Outcomes

If Trump's causal claim is **true** ("The wall caused El Paso to have fewer murders"), which should be true?

$$\textrm{Murders}_{\textrm{El Paso}}(\textrm{Wall})  < \color{red}{\textrm{Murders}_{\textrm{El Paso}}(\textrm{No Wall})} \tag{1}$$

$$\textrm{Murders}_{\textrm{El Paso}}(\textrm{Wall}) > \color{red}{\textrm{Murders}_{\textrm{El Paso}}(\textrm{No Wall})} \tag{2}$$

$$\textrm{Murders}_{\textrm{El Paso}}(\textrm{Wall}) = \color{red}{\textrm{Murders}_{\textrm{El Paso}}(\textrm{No Wall})} \tag{3}$$

## Counterfactuals and Potential Outcomes

> **"The border city of El Paso, Tex., used to have extremely high rates of violent crime — one of the highest in the entire country, and considered one of our nation’s most dangerous cities. Now, immediately upon its building, with a powerful barrier in place, El Paso is one of the safest cities in our country."**

Implies:

$$\textrm{Murders}_{\textrm{El Paso}}(\textrm{Wall})  < \color{red}{\textrm{Murders}_{\textrm{El Paso}}(\textrm{No Wall})}$$

## Counterfactuals and Potential Outcomes

If the claim is that "The wall caused El Paso to have fewer murders", or

$$\textrm{Murders}_{\textrm{El Paso}}(\textrm{Wall})  < \color{red}{\textrm{Murders}_{\textrm{El Paso}}(\textrm{No Wall})}$$

### What kinds of evidence would help assess whether this claim is true?

## Conclusion:

Causality is **counterfactual**

- this is not a simple, intuitive way of thinking
- this complicates providing evidence

We will see:

- different types of causal claims
- problems in testing causal claims
- focus on solutions (for some causal claims)

